version: "3.9"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: odak_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      JWT_SECRET: "odakmat_super_secret_key_32_chars_min!!"
      JWT_ALG: "HS256"
      JWT_EXPIRE_MIN: 1440
      FLASK_APP: main.py
      DATABASE_URL: postgresql+psycopg2://odak:odak123@db:5432/odakdb
    volumes:
      - ./backend:/app/backend
    command: gunicorn -w 2 -b 0.0.0.0:8000 main:app
  db:
    image: postgres:16
    container_name: odak_db
    restart: always
    environment:
      POSTGRES_USER: odak
      POSTGRES_PASSWORD: odak123
      POSTGRES_DB: odakdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
